os:
  - linux
  - osx

sudo: false

language:
  - android
  - cpp

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-24.0.1
    - android-22
    - extra

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22

compiler:
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang

before_script:
  - "export CC=/usr/bin/clang"
  - "export CXX=/usr/bin/clang++"
  - "if [ $TRAVIS_OS_NAME == osx ]; then \
        brew update;
        brew install android-ndk ant;
        export ANDROID_NDK=/usr/local/opt/android-ndk;
        export PATH=${PATH}:${ANDROID_NDK};
    fi"
  - "if [ $TRAVIS_OS_NAME == linux ]; then \
        wget --quiet --continue http://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip -O ndk.zip;
        unzip -o -q ndk.zip;
        export ANDROID_NDK=`pwd`/android-ndk-r12b;
        export PATH=${PATH}:${ANDROID_NDK};
    fi"

script:
  - ./scripts/travis-build.sh
