os:
  - linux
  - osx

sudo: false

language:
  - cpp

compiler:
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

script:
  - cmake --version
  - ./scripts/cmake-make.sh -j4

notifications:
  email:
    - shervinaflatooni@gmail.com
