matrix:
  include:
    # linux emscripten
    - os: linux
      services:
        - docker
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
      env:
        - BUILD_TYPE=emscripten
      group: travis_latest
      dist: trusty

before_script:
  - uname -a
  - if [ $TRAVIS_OS_NAME == linux ] && [ $BUILD_TYPE == emscripten ]; then 
      docker run -dit --name emscripten -e TRAVIS_OS_NAME='linux' -e BUILD_TYPE='emscripten' -v `pwd`:/engine -w /engine trzeci/emscripten:sdk-incoming-64bit bash ; 
      docker exec -it emscripten apt-get update ;
      docker exec -it emscripten apt-get install -y cmake wget ;
    fi

script:
  - if [ $TRAVIS_OS_NAME == linux ] && [ $BUILD_TYPE == emscripten ]; then 
      docker exec -it emscripten ./scripts/travis-build.sh ;
    else
      ./scripts/travis-build.sh ;
    fi 