os:
  - linux
  - osx

sudo: false

language:
  - cpp
  - android

android:
  components:
    - build-tools-20.0.0

    # The SDK version used to compile your project
    - android-17

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22

compiler:
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang


before_script:
  - "if [ $TRAVIS_OS_NAME == osx ]; then \
        brew update;
        brew install android-sdk android-ndk ant;
        export ANDROID_SDK=/usr/local/opt/android-sdk;
        export ANDROID_NDK=/usr/local/opt/android-ndk;
        export PATH=${PATH}:${ANDROID_SDK}/tools:${ANDROID_SDK}/platform-tools:${ANDROID_NDK};
    fi"
  - "if [ $TRAVIS_OS_NAME == linux ]; then \
        wget --quiet --continue http://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip -O ndk.zip;
        unzip -o -q ndk.zip;

        wget --quiet --continue http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz;
        tar -xzf android-sdk_r24.4.1-linux.tgz;
        echo \"y\" | ./android-sdk-linux/tools/android update sdk -a -u -s -t platform-tools, build-tools;
        export ANDROID_SDK=`pwd`/android-sdk-linux;
        export ANDROID_HOME=$ANDROID_SDK;
        export ANDROID_NDK=`pwd`/android-ndk-r12b;
        export PATH=${PATH}:${ANDROID_SDK}/tools:${ANDROID_SDK}/platform-tools:${ANDROID_NDK};
    fi"

script:
  - cmake --version
  - echo $ANDROID_NDK
  - ANDROID_NDK=$ANDROID_NDK ./scripts/cmake-android.sh -j4
  - ./scripts/cmake-make.sh -j4

notifications:
  email:
    - shervinaflatooni@gmail.com
